### ISSUE TITLE
Error on watch command

### ISSUE THREAD

**Issue by albohlabs** [khalillechelt/grunt-compass#28]
I get this error when running the watch command:

```
Running "watch" task
Waiting...OK
>> File "css/scss/global.scss" changed.

timers.js:103
            if (!process.listeners('uncaughtException').length) throw e;
                                                                      ^
Error
    at /usr/local/lib/node_modules/grunt/lib/util/task.js:47:25
    at Object.<anonymous> (/usr/local/lib/node_modules/grunt/lib/util/task.js:390:2)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/grunt/lib/grunt/utils.js:17:14)
    at Module._compile (module.js:449:26)
```

and here is my grunt.js file:

``` javascript
/*global module:false*/
module.exports = function(grunt) {

  // Project configuration.
  grunt.initConfig({
    watch: {
      files: ['css/scss/*'],
      tasks: ['compass-clean compass']
    },
    compass: {
      dest: {
        src: 'css/scss',
        dest: 'css',
        outputstyle: 'compressed',
        linecomments: false,
        forcecompile: true,
        debugsass: false,
        relativeassets: true
      }
    },
  });

  grunt.loadNpmTasks('grunt-compass');

  grunt.registerTask('default', 'watch');
};

```

If only compass-clean or compass is defined as a task, no error is raised. Same behavior if i define it like: `tasks: ['compass-clean',  'compass']`

node `v0.8.15`

**Comment by khalillechelt** [comment]
The watch tasks need to be an array. 

E.g. tasks: ['compass-clean', 'compass']

**Comment by albohlabs** [comment]
But in [gruntjs example](https://github.com/cowboy/javascript-hooker/blob/master/grunt.js#L33) the tasks are concatenated.

**Comment by khalillechelt** [comment]
Well did you try it with the array?

**Comment by khalillechelt** [comment]
What works?

**Comment by albohlabs** [comment]
> Well did you try it with the array?

Yes.

> What works?

It works with an array.

**Comment by khalillechelt** [comment]
And did you try 

```
tasks: 'compass-clean compass'
```

?

Because that is how Ben does it in the example. 

Not 

```
tasks: ['compass-clean compass']
```
